"""Protocol v3 primitives that are implemented task by task.

Only modules whose numbered implementation task reached ``DONE_100`` may be
imported here as executable Protocol v3 behavior.
"""

from .boundaries import (
    ACTIVATION_DELAY_HOURS,
    DEPLOYMENT_ANCHOR_DAY_UTC,
    OUTER_ORIGINS,
    PROCESS_OOS_DAYS,
    TRAINING_DAYS_PER_ORIGIN,
    BoundaryValidationError,
    LateButtonResolution,
    MonthlyOriginBoundary,
    MonthlyProcessBoundaryPlan,
    build_monthly_process_boundary_plan,
    monthly_anchor,
    resolve_process_end_exclusive,
    resolve_target_anchor_for_button,
    validate_monthly_process_boundary_plan,
)
from .global_budget import (
    CURRENT_REFIT_RUNS,
    MAX_TOTAL_CYCLES,
    MAX_TOTAL_FINALISTS,
    MAX_TOTAL_GENERATED,
    MAX_TOTAL_TESTED,
    MAX_TOTAL_WALK_FORWARD,
    SELECTION_RUNS_TOTAL,
    GlobalBudgetUsage,
    GlobalSearchBudgetEnvelope,
    validate_global_budget_usage,
)
from .pipeline import (
    PIPELINE_CONTRACT_PATH,
    PIPELINE_CONTRACT_VERSION,
    PIPELINE_GENERATION_PREFIX,
    PIPELINE_SCHEMA_VERSION,
    PRE_RUN_MANIFEST_SCHEMA_VERSION,
    BudgetUsage,
    PipelineContractError,
    PipelineGeneration,
    PreRunManifest,
    SearchBudgetPolicy,
    build_pipeline_generation,
    build_pre_run_manifest,
    derive_seed,
    origin_cycle_seed,
    stagnation_stop_reason,
    validate_actual_cycle_counts,
    validate_budget_usage,
    validate_pipeline_contract,
    validate_pipeline_generation,
    validate_pre_run_manifest,
)
from . import trial_ledger as _trial_ledger
from .trial_ledger import (
    CANONICAL_HISTORICAL_IMPORT_PATH,
    DEVELOPMENT_DSR_INSUFFICIENT,
    DEVELOPMENT_DSR_READY,
    NO_TRADE,
    PERMANENT_TRIAL_COUNTER_NAMESPACE,
    TRADING_CANDIDATE,
    HistoricalImportResult,
    TrialLedgerError,
    TrialLedgerSnapshot,
    TrialLedgerStatus,
    TrialRecord,
    append_trial,
    assert_release_decision_allowed,
    attach_trial_daily_series,
    build_canonical_historical_import_digest,
    build_trial_record,
    import_canonical_historical_lower_bound,
    import_historical_reports,
    initialize_trial_ledger,
    read_trial_ledger,
    record_cache_reuse,
    validate_historical_lower_bound_manifest,
    validate_trial_record,
)
from .trial_history_gate import attest_complete_trial_inventory

# Make even direct submodule imports resolve to the reconciled fail-closed gate.
_trial_ledger.attest_complete_trial_inventory = attest_complete_trial_inventory

__all__ = [
    "ACTIVATION_DELAY_HOURS",
    "CANONICAL_HISTORICAL_IMPORT_PATH",
    "CURRENT_REFIT_RUNS",
    "DEPLOYMENT_ANCHOR_DAY_UTC",
    "DEVELOPMENT_DSR_INSUFFICIENT",
    "DEVELOPMENT_DSR_READY",
    "MAX_TOTAL_CYCLES",
    "MAX_TOTAL_FINALISTS",
    "MAX_TOTAL_GENERATED",
    "MAX_TOTAL_TESTED",
    "MAX_TOTAL_WALK_FORWARD",
    "NO_TRADE",
    "OUTER_ORIGINS",
    "PERMANENT_TRIAL_COUNTER_NAMESPACE",
    "PIPELINE_CONTRACT_PATH",
    "PIPELINE_CONTRACT_VERSION",
    "PIPELINE_GENERATION_PREFIX",
    "PIPELINE_SCHEMA_VERSION",
    "PRE_RUN_MANIFEST_SCHEMA_VERSION",
    "PROCESS_OOS_DAYS",
    "SELECTION_RUNS_TOTAL",
    "TRADING_CANDIDATE",
    "TRAINING_DAYS_PER_ORIGIN",
    "BoundaryValidationError",
    "BudgetUsage",
    "GlobalBudgetUsage",
    "GlobalSearchBudgetEnvelope",
    "HistoricalImportResult",
    "LateButtonResolution",
    "MonthlyOriginBoundary",
    "MonthlyProcessBoundaryPlan",
    "PipelineContractError",
    "PipelineGeneration",
    "PreRunManifest",
    "SearchBudgetPolicy",
    "TrialLedgerError",
    "TrialLedgerSnapshot",
    "TrialLedgerStatus",
    "TrialRecord",
    "append_trial",
    "assert_release_decision_allowed",
    "attach_trial_daily_series",
    "attest_complete_trial_inventory",
    "build_canonical_historical_import_digest",
    "build_monthly_process_boundary_plan",
    "build_pipeline_generation",
    "build_pre_run_manifest",
    "build_trial_record",
    "derive_seed",
    "import_canonical_historical_lower_bound",
    "import_historical_reports",
    "initialize_trial_ledger",
    "monthly_anchor",
    "origin_cycle_seed",
    "read_trial_ledger",
    "record_cache_reuse",
    "resolve_process_end_exclusive",
    "resolve_target_anchor_for_button",
    "stagnation_stop_reason",
    "validate_actual_cycle_counts",
    "validate_budget_usage",
    "validate_global_budget_usage",
    "validate_historical_lower_bound_manifest",
    "validate_monthly_process_boundary_plan",
    "validate_pipeline_contract",
    "validate_pipeline_generation",
    "validate_pre_run_manifest",
    "validate_trial_record",
]
