"""Stable public Protocol v3 report API for Task 11.

Only validated Task-11 report and evidence-window objects cross this facade.
Legacy final/adoption consumers remain separate and cannot be reached here.
"""

from .reporting import (
    FORWARD_REGISTRATION_ROOT,
    FORWARD_SHADOW_MONTH,
    MONTHLY_PROCESS_OOS,
    PROCESS_OOS_CALENDAR_DAYS,
    PROTOCOL_V3_PIPELINE_FINAL,
    PROTOCOL_V3_RESEARCH,
    REPORT_CONTRACT_PATH,
    REPORT_CONTRACT_SCHEMA,
    REPORT_CONTRACT_VERSION,
    REPORT_KINDS,
    REPORT_SCHEMA_VERSION,
    REPORT_STORAGE_ROOTS,
    RESEARCH_CHALLENGER_SHADOW,
    TARGET_USDC_PER_CALENDAR_DAY,
    WINDOW_REGISTRATION_SCHEMA_VERSION,
    ProtocolV3Report,
    ProtocolV3ReportError,
    ProtocolV3WindowRegistration,
    assert_sealed_final_window_excludes_visible_forward_months,
    build_forward_window_registration,
    build_protocol_v3_report,
    load_report_contract,
    read_forward_window_registration,
    read_protocol_v3_report,
    validate_protocol_v3_report,
    validate_report_contract,
    validate_window_registration,
    write_forward_window_registration,
    write_protocol_v3_report,
)

__all__ = [
    "FORWARD_REGISTRATION_ROOT",
    "FORWARD_SHADOW_MONTH",
    "MONTHLY_PROCESS_OOS",
    "PROCESS_OOS_CALENDAR_DAYS",
    "PROTOCOL_V3_PIPELINE_FINAL",
    "PROTOCOL_V3_RESEARCH",
    "REPORT_CONTRACT_PATH",
    "REPORT_CONTRACT_SCHEMA",
    "REPORT_CONTRACT_VERSION",
    "REPORT_KINDS",
    "REPORT_SCHEMA_VERSION",
    "REPORT_STORAGE_ROOTS",
    "RESEARCH_CHALLENGER_SHADOW",
    "TARGET_USDC_PER_CALENDAR_DAY",
    "WINDOW_REGISTRATION_SCHEMA_VERSION",
    "ProtocolV3Report",
    "ProtocolV3ReportError",
    "ProtocolV3WindowRegistration",
    "assert_sealed_final_window_excludes_visible_forward_months",
    "build_forward_window_registration",
    "build_protocol_v3_report",
    "load_report_contract",
    "read_forward_window_registration",
    "read_protocol_v3_report",
    "validate_protocol_v3_report",
    "validate_report_contract",
    "validate_window_registration",
    "write_forward_window_registration",
    "write_protocol_v3_report",
]
